version: '3'
services:
  bot:
    build: ./docker/bot
    ports :
      - "80:80"
    volumes:
      - ./bot:/bot
    working_dir: /bot
    depends_on:
      - mongodb
    networks:
      - bdd
      - exterior

  mongodb:
    image: mongo:bionic
    volumes:
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/data/db/:/data/db/
      - ./mongodb/data/log/:/var/log/mongodb/
      - ./mongodb/initdb.d/:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    networks:
      - bdd
networks:
  bdd:
    internal: true
  exterior:
    internal: false