version: '3'
services:
  bot:
    build: ./docker/bot
    restart: always
    volumes:
      - ./bot:/bot
      - ./logs:/logs
      - ./exported_stats:/exported_stats
      - ./npm_cache:/npm_cache
    working_dir: /bot
    environment:
      npm_config_cache: /npm_cache
    depends_on:
      - mongodb
    networks:
      - bdd
      - exterior

  crontab:
    build: ./docker/crontab
    volumes:
      - ./bot:/bot
      - ./logs:/logs
      - ./script_logs:/script_logs
      - ./cronjobs:/cronjobs
      - ./crontab:/etc/cron.d/crontab
    depends_on:
      - mongodb
    networks:
      - bdd
      - exterior

  mongodb:
    image: mongo:bionic
    volumes:
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/data/db/:/data/db/
      - ./mongodb/data/log/:/var/log/mongodb/
      - ./mongodb/initdb.d/:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    networks:
      - bdd

networks:
  bdd:
    internal: true
  exterior:
    internal: false
